FROM node:lts-alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm config set registry https://registry.npmjs.org/ \
 && npm config set always-auth false \
 && npm ci
COPY . .
CMD ["npm", "run", "start"]