version: "3"
services:
  server:
    image: bhassan310/multi-container-api
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: bhassan310/multi-container-client
    mem_limit: 128m
    hostname: client
  worker:
    image: bhassan310/multi-container-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: bhassan310/multi-container-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"